[Defaults]
# Directory where files will be saved in GUI mode.
Directory = ~/Music

# Default recording sampling rate.
# Lowering this value may will change the pitch of
# the recoring output.
SamplingRate = 48000

# Default channels: 2 ( Stereo ), 1 ( Mono ).
Channels = 2
